services:
  db:
    image: postgres:14
    container_name: local-db
    restart: always
    environment:
      POSTGRES_DB: exchange_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - local-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: local-backend
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    networks:
      - local-net
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: local-frontend
    ports:
      - "3000:3000"
    networks:
      - local-net
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    command: npm start
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  postgres_data:

networks:
  local-net:
