# Generated by Django 5.2 on 2025-05-26 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='available',
        ),
        migrations.AddField(
            model_name='card',
            name='forTrade',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
